name: iqra_islamic_wisdom
description: An Islamic Wisdom app with Quran, Hadith, and Qibla features.

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_qiblah: ^3.1.0+1
  geolocator: ^13.0.4
  shared_preferences: ^2.3.2
  flutter_tts: ^4.0.2
  url_launcher: ^6.3.0
  google_fonts: ^6.2.1
  provider: ^6.1.2

flutter:
  uses-material-design: true
  assets:
    - assets/quran/
    - assets/hadith/
    - assets/images/
    - assets/fonts/
