name: iqra_islamic_wisdom
description: A Quran and Islamic wisdom application

publish_to: 'none'

version: 3.3.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/audio/
    - assets/fonts/
    - assets/quran_data/

  fonts:
    - family: PremiumNastaliq
      fonts:
        - asset: assets/fonts/PremiumNastaliq.ttf
