name: iqra_islamic_wisdom
description: An Islamic Wisdom App with Quran, Hadith, Qiblah, and Islamic Knowledge.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: '^3.5.0'
  flutter: '>=3.24.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  share_plus: ^10.0.0
  path_provider: ^2.1.3
  url_launcher: ^6.3.0
  flutter_tts: ^4.0.2
  flutter_qiblah: ^3.1.0+1
  geolocator: ^13.0.4
  http: ^1.2.2
  provider: ^6.1.2
  intl: ^0.19.0
  flutter_local_notifications: ^17.1.2
  permission_handler: ^11.3.1
  sqflite: ^2.4.0
  flutter_svg: ^2.0.10+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/quran/
    - assets/hadith/
    - assets/images/
    - assets/fonts/

  fonts:
    - family: UthmanicHafs
      fonts:
        - asset: assets/fonts/UthmanicHafs1.ttf
