dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  share_plus: ^10.0.0
  path_provider: ^2.1.3
  url_launcher: ^6.3.0
  flutter_tts: ^4.0.2
  flutter_qiblah: ^3.1.0+1
  geolocator: ^13.0.4
  http: ^1.2.2
  provider: ^6.1.2
  intl: ^0.19.0
  flutter_local_notifications: ^17.1.2
  permission_handler: ^11.3.1
  sqflite: ^2.4.0
  flutter_svg: ^2.0.10+1
