name: Fix Android Embedding and Build APK

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  fix_and_build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.3'

      - name: Create new Flutter project (v2 embedding)
        run: |
          flutter create fixed_app
          rm -rf fixed_app/lib fixed_app/assets fixed_app/pubspec.yaml
          cp -r lib fixed_app/
          cp -r assets fixed_app/ || true
          cp pubspec.yaml fixed_app/

      - name: Get dependencies
        working-directory: fixed_app
        run: flutter pub get

      - name: Build release APK
        working-directory: fixed_app
        run: flutter build apk --release --no-shrink

      - name: Upload generated APK
        uses: actions/upload-artifact@v4
        with:
          name: Iqra_Islamic_Wisdom_v3.4_Fixed
          path: fixed_app/build/app/outputs/flutter-apk/app-release.apk
