name: Build Flutter APK
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Repository checkout
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Setup Flutter
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'

      # Step 3: Get dependencies
      - name: Get dependencies
        run: flutter pub get

      # Step 4: Build release APK
      - name: Build APK
        run: flutter build apk --release

      # Step 5: Upload artifact
      - name: Upload release APK
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
