name: Build APK
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Build with Different Method
        run: |
          # Temporary directory
          mkdir /tmp/build_app
          cd /tmp/build_app
          
          # Flutter setup
          git clone https://github.com/flutter/flutter.git -b stable
          export PATH="$PATH:/tmp/build_app/flutter/bin"
          
          # Project
          flutter create --platforms android myapp
          cd myapp
          
          # Debug build (lightweight)
          flutter build apk --debug
        
      - name: Upload Debug APK
        uses: actions/upload-artifact@v4
        with:
          name: debug-app
          path: /tmp/build_app/myapp/build/app/outputs/flutter-apk/app-debug.apk
