name: Build Flutter APK

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  build_apk:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.24.4'

    - name: Enable Android SDK license accept
      run: yes | flutter doctor --android-licenses

    - name: Get dependencies
      run: flutter pub get

    - name: Build release APK
      run: flutter build apk --release --no-shrink

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: app-release-apk
        path: build/app/outputs/flutter-apk/app-release.apk
